# This playbook saves the trouble of running each of the following playbooks
# individually, and is provided for convenience. After "vagrant up", this
# playbook will be run on the new Vagrant box.

- include: provision.yml
- include: configure.yml

# Because this playbook targets the "vagrant" inventory host, it will only be
# run for the Vagrant box, and skipped otherwise.
- include: vagrant-link.yml
