# Provision server. This playbook must be run when a server is first created
# and is typically only run once. It may be run again if you make server-level
# changes or need to update any installed apt modules to their latest versions.
# If you were creating a new AMI or base box, you'd do so after running only
# this playbook.

- hosts: all
  become: yes
  become_method: sudo
  roles:
    - {role: base, tags: base}
